@echo off
echo Building WhatsApp Clone with CRM...

echo Installing dependencies...
call npm install

echo Generating Prisma client...
call npx prisma generate

echo Building application...
call npm run build

echo Starting application...
call npm run start

echo Application is running at http://localhost:3000 